#Criar trigger para registrar um LOG das atualizações das Tabela Professor. No Log deve existir:

 #          1-  código do usuário que fez a alteração;

  #         2-  chave primaria do registro alterado;

   #        3-  Tipo de alteração realizado (INSERT ou UPDATE ou DELETE);

    #       4-  Data e Hora da alteração.



#Entregar a estrutura da Tabela de LOG ( pode ser chamada Tabela_Log_Professor ) ;

#e o Código da(s) Trigger(s).

DROP TABLE IF EXISTS TB_LOG_PROFESSOR;
DROP TRIGGER IF EXISTS TGR_TB_PROFESSOR_INSERT;
DROP TRIGGER IF EXISTS TGR_TB_PROFESSOR_UPDATE;
DROP TRIGGER IF EXISTS TGR_TB_PROFESSOR_DELETE;

CREATE TABLE TB_LOG_PROFESSOR (
	USUARIO VARCHAR(40) NOT NULL,
	COD_PROF INT,
	TIPO_ALTERACAO VARCHAR(10),
	DATA_ALTERACAO DATETIME
);

DELIMITER $$
CREATE TRIGGER TGR_TB_PROFESSOR_INSERT BEFORE INSERT 
ON TB_PROFESSOR
FOR EACH ROW
BEGIN
	INSERT INTO TB_LOG_PROFESSOR (USUARIO, COD_PROF, TIPO_ALTERACAO, DATA_ALTERACAO) VALUES (CURRENT_USER(), NEW.COD_PROF, 'INSERT', NOW());
END $$

CREATE TRIGGER TGR_TB_PROFESSOR_UPDATE AFTER UPDATE 
ON TB_PROFESSOR
FOR EACH ROW
BEGIN
	INSERT INTO TB_LOG_PROFESSOR (USUARIO, COD_PROF, TIPO_ALTERACAO, DATA_ALTERACAO) VALUES (CURRENT_USER(), NEW.COD_PROF, 'UPDATE', NOW());
END $$

CREATE TRIGGER TGR_TB_PROFESSOR_DELETE AFTER DELETE 
ON TB_PROFESSOR
FOR EACH ROW
BEGIN
	INSERT INTO TB_LOG_PROFESSOR (USUARIO, COD_PROF, TIPO_ALTERACAO, DATA_ALTERACAO) VALUES (CURRENT_USER(), OLD.COD_PROF, 'DELETE', NOW());
END $$
DELIMITER ;

INSERT INTO TB_PROFESSOR(COD_PROF, COD_DEPTO, COD_TIT, NOME_PROF) VALUES (5, 'INF01', 2, 'Marcus');
INSERT INTO TB_PROFESSOR(COD_PROF, COD_DEPTO, COD_TIT, NOME_PROF) VALUES (6, 'MAT01', 2, 'Wellington');

UPDATE TB_PROFESSOR SET NOME_PROF = 'Marcus Vasconcelos' WHERE COD_PROF = 5;
UPDATE TB_PROFESSOR SET COD_TIT = 1 WHERE COD_PROF = 6;
    
DELETE FROM TB_PROFESSOR WHERE COD_PROF = 5;
DELETE FROM TB_PROFESSOR WHERE COD_PROF = 6;
 
SELECT USUARIO, COD_PROF, TIPO_ALTERACAO, DATA_ALTERACAO FROM TB_LOG_PROFESSOR;

